"use client";
import { Bot, ChevronDown, ExternalLink, Play, SkipForward, Clock, Undo2, CircleDot } from "lucide-react";
import Link from "next/link";
import { useState, type ReactNode } from "react";
import { MISTAKE_TYPES, PRIORITY_LABEL, TASK_TYPE_LABEL } from "@/lib/roadmap/constants";
import { IDX } from "@/lib/roadmap/client-index";
import { RESOURCES } from "@/lib/client/resources";
import { useLearning } from "@/lib/client/store";
import { useDerived, useLS } from "@/lib/client/hooks";
import type { Task } from "@/lib/roadmap/types";
import type { CheckScope, DsaMode, DsaOutcome } from "@/lib/state/events";
import { dayProgress, statusOf } from "@/lib/state/selectors";
import { Badge, Button, Checkbox, cx, inputCls, Modal, selectCls } from "./ui";

const ROLE_MODE: Record<string, DsaMode> = { "first-pass": "first", "second-pass": "cold", "spaced-resolve": "revision", timed: "timed", other: "first" };

export function TaskItem({ task, showDay, highlight }: { task: Task; showDay?: boolean; highlight?: boolean }) {
  const { state, dispatch } = useLS();
  const timer = useLearning((s) => s.timer);
  const startTimer = useLearning((s) => s.startTimer);
  const [open, setOpen] = useState(!!highlight);
  const [dsa, setDsa] = useState<string | null>(null);
  const status = statusOf(state, task.id);
  const done = status === "completed";
  const note = state.notes[`task:${task.id}`]?.text ?? "";
  const res = task.resource ? RESOURCES[task.resource] : undefined;
  const [head, ...rest] = task.text.split(/(?<=\.)\s+/);
  return (
    <li id={task.id} className={cx("rounded-lg border bg-surface transition-colors", highlight ? "border-accent" : "border-line", (status === "skipped" || status === "deferred") && "opacity-70")}>
      <div className="flex items-start gap-2 p-2.5">
        <div className="pt-0.5">
          <Checkbox checked={done} onChange={(v) => dispatch(v ? "TASK_COMPLETED" : "TASK_UNCOMPLETED", { taskId: task.id })} label={<span className="sr-only">Complete task</span>} />
        </div>
        <button className="min-w-0 flex-1 text-left" onClick={() => setOpen((v) => !v)} aria-expanded={open}>
          <div className={cx("text-[13.5px] leading-snug", done && "text-muted line-through decoration-faint")}>{head}</div>
          <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
            {showDay && <Badge>W{task.week} D{task.day}</Badge>}
            <Badge tone={task.priority === "M" ? "accent" : "neutral"}>{PRIORITY_LABEL[task.priority]}</Badge>
            <Badge>{TASK_TYPE_LABEL[task.type]}</Badge>
            <span className="font-mono text-[11px] text-muted">{task.minutes} min</span>
            {task.auto && <Badge tone="info" title="Recall task generated by the roadmap">recall</Badge>}
            {task.supporting && <Badge tone="info" title="Supporting MERN task — counts toward the roadmap">MERN</Badge>}
            {status === "in_progress" && <Badge tone="accent"><CircleDot className="size-3" /> in progress</Badge>}
            {status === "skipped" && <Badge tone="bad">skipped</Badge>}
            {status === "deferred" && <Badge tone="info">deferred</Badge>}
            {note && <Badge>note</Badge>}
          </div>
        </button>
        <ChevronDown className={cx("mt-1 size-4 shrink-0 text-faint transition-transform", open && "rotate-180")} />
      </div>
      {open && (
        <div className="space-y-3 border-t border-line px-3 pb-3 pt-2.5 text-sm">
          {rest.length > 0 && <p className="text-muted">{rest.join(" ")}</p>}
          <div className="flex flex-wrap gap-2 text-xs">
            {res && (
              <a href={res.url || undefined} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-info hover:underline">
                <ExternalLink className="size-3" /> {res.name}
              </a>
            )}
            {task.project && (
              <Link href={`/projects/${task.project}`} className="text-info hover:underline">
                Project: {IDX.existingProjects.find((p) => p.id === task.project)?.name.split(" — ")[0]}
              </Link>
            )}
            {task.problemIds?.map((pid) => (
              <Link key={pid} href={`/dsa?problem=${pid}`} className="text-info hover:underline">
                {IDX.dsa.find((d) => d.id === pid)?.name}
              </Link>
            ))}
          </div>
          <div className="flex flex-wrap gap-1.5">
            {status !== "in_progress" && !done && (
              <Button size="sm" onClick={() => dispatch("TASK_STARTED", { taskId: task.id })}>
                <CircleDot className="size-3.5" /> Start
              </Button>
            )}
            {!timer && (
              <Button size="sm" onClick={() => { startTimer(task.id); if (!done) dispatch("TASK_STARTED", { taskId: task.id }); }}>
                <Play className="size-3.5" /> Timer
              </Button>
            )}
            {!done && status !== "skipped" && (
              <Button size="sm" variant="ghost" onClick={() => dispatch("TASK_SKIPPED", { taskId: task.id })}>
                <SkipForward className="size-3.5" /> Skip
              </Button>
            )}
            {!done && status !== "deferred" && (
              <Button size="sm" variant="ghost" onClick={() => dispatch("TASK_DEFERRED", { taskId: task.id })}>
                <Clock className="size-3.5" /> Defer
              </Button>
            )}
            {status !== "not_started" && (
              <Button size="sm" variant="ghost" onClick={() => dispatch("TASK_UNCOMPLETED", { taskId: task.id })}>
                <Undo2 className="size-3.5" /> Reset
              </Button>
            )}
            {task.problemIds?.[0] && (
              <Button size="sm" variant="ghost" onClick={() => setDsa(task.problemIds![0])}>
                Log DSA attempt
              </Button>
            )}
            <Link href={`/tutor?task=${task.id}`} className="inline-flex h-7 items-center gap-1 rounded-md px-2.5 text-xs text-muted hover:bg-surface-2 hover:text-ink">
              <Bot className="size-3.5" /> Study with Claude
            </Link>
          </div>
          <NoteField noteKey={`task:${task.id}`} placeholder="Notes for this task (saved locally, synced when signed in)…" />
        </div>
      )}
      {dsa && <DsaLogDialog problemId={dsa} taskId={task.id} defaultMode={ROLE_MODE[task.dsaRole ?? "other"]} onClose={() => setDsa(null)} />}
    </li>
  );
}

export function NoteField({ noteKey, placeholder, rows = 3, label }: { noteKey: string; placeholder?: string; rows?: number; label?: ReactNode }) {
  const { state, dispatch } = useLS();
  const saved = state.notes[noteKey]?.text ?? "";
  const [val, setVal] = useState<string | null>(null);
  const v = val ?? saved;
  return (
    <label className="block">
      {label && <span className="mb-1 block text-xs font-medium text-muted">{label}</span>}
      <textarea
        className={cx(inputCls, "h-auto min-h-16 py-2 leading-relaxed")}
        rows={rows}
        value={v}
        placeholder={placeholder}
        onChange={(e) => setVal(e.target.value)}
        onBlur={() => {
          if (val !== null && val !== saved) dispatch("NOTE_SAVED", { key: noteKey, text: val });
          setVal(null);
        }}
      />
    </label>
  );
}

export function CheckList({ items, keyOf, scope, render }: { items: string[]; keyOf: (i: number) => string; scope: CheckScope; render?: (item: string, i: number) => ReactNode }) {
  const { state, dispatch } = useLS();
  return (
    <ul className="space-y-0.5">
      {items.map((it, i) => {
        const key = keyOf(i);
        return (
          <li key={key}>
            <Checkbox checked={!!state.checks[key]?.on} onChange={(on) => dispatch("CHECK_SET", { scope, key, on })} label={render ? render(it, i) : it} />
          </li>
        );
      })}
    </ul>
  );
}

/** 364 cells: 52 weeks × 7 days. Colour = share of the day's tasks completed; amber ring = current position. */
export function YearMap({ current }: { current: number }) {
  const cells = useDerived((s) => IDX.days.map((d) => dayProgress(s, d.idx)), []);
  const level = (pct: number) => (pct >= 100 ? 1 : pct >= 66 ? 0.72 : pct >= 33 ? 0.48 : pct > 0 ? 0.26 : 0);
  return (
    <div className="overflow-x-auto scroll-thin">
      <div className="grid w-max grid-flow-col grid-rows-7 gap-[3px]" role="img" aria-label="Year map of roadmap days">
        {IDX.days.map((d, i) => {
          const p = cells[i];
          const l = level(p.pct);
          return (
            <Link
              key={d.idx}
              href={`/roadmap/${d.week}`}
              title={`W${d.week} D${d.day} · ${d.title} — ${p.done}/${p.total} tasks`}
              className={cx("size-[11px] rounded-[2px]", i === current && "ring-2 ring-accent ring-offset-1 ring-offset-surface")}
              style={{ background: l ? `color-mix(in srgb, var(--good) ${Math.round(l * 100)}%, var(--cell-0))` : "var(--cell-0)" }}
            />
          );
        })}
      </div>
      <div className="mt-2 flex items-center gap-3 text-[11px] text-faint">
        <span>W1</span>
        <span className="flex-1 border-t border-dashed border-line" />
        <span>W52</span>
      </div>
    </div>
  );
}

export function DsaLogDialog({ problemId, taskId, defaultMode = "first", onClose }: { problemId?: string; taskId?: string; defaultMode?: DsaMode; onClose: () => void }) {
  const { state, dispatch } = useLS();
  const [pid, setPid] = useState(problemId ?? "");
  const [mode, setMode] = useState<DsaMode>(defaultMode);
  const [outcome, setOutcome] = useState<DsaOutcome>("solved");
  const [minutes, setMinutes] = useState(25);
  const [mistake, setMistake] = useState("");
  const [notes, setNotes] = useState("");
  const [markTask, setMarkTask] = useState(true);
  const p = IDX.dsa.find((d) => d.id === pid);
  const taskDone = taskId ? statusOf(state, taskId) === "completed" : true;
  return (
    <Modal open onOpenChange={(v) => !v && onClose()} title="Log DSA attempt" description={p ? `${p.name} · ${p.difficulty} · ${p.category}` : "Record an honest attempt — failures teach the revision schedule too."}>
      <div className="space-y-3 text-sm">
        {!problemId && (
          <label className="block">
            <span className="mb-1 block text-xs text-muted">Problem</span>
            <select className={cx(selectCls, "w-full")} value={pid} onChange={(e) => setPid(e.target.value)}>
              <option value="">Choose a problem…</option>
              {IDX.dsa.map((d) => (
                <option key={d.id} value={d.id}>
                  {d.name} — {d.category}
                </option>
              ))}
            </select>
          </label>
        )}
        <div className="grid grid-cols-2 gap-3">
          <label className="block">
            <span className="mb-1 block text-xs text-muted">Mode</span>
            <select className={cx(selectCls, "w-full")} value={mode} onChange={(e) => setMode(e.target.value as DsaMode)}>
              <option value="first">First attempt</option>
              <option value="cold">Cold re-solve</option>
              <option value="revision">Spaced revision</option>
              <option value="timed">Timed</option>
            </select>
          </label>
          <label className="block">
            <span className="mb-1 block text-xs text-muted">Minutes</span>
            <input type="number" min={0} max={600} className={inputCls} value={minutes} onChange={(e) => setMinutes(Math.max(0, Math.min(600, Number(e.target.value) || 0)))} />
          </label>
        </div>
        <div>
          <span className="mb-1 block text-xs text-muted">Outcome</span>
          <div className="flex gap-2">
            {(["solved", "partial", "unsolved"] as DsaOutcome[]).map((o) => (
              <Button key={o} size="sm" variant={outcome === o ? (o === "solved" ? "good" : o === "unsolved" ? "danger" : "primary") : "default"} onClick={() => setOutcome(o)}>
                {o === "solved" ? "Solved" : o === "partial" ? "Partially" : "Not solved"}
              </Button>
            ))}
          </div>
        </div>
        <label className="block">
          <span className="mb-1 block text-xs text-muted">Mistake type {outcome === "solved" && "(optional)"}</span>
          <select className={cx(selectCls, "w-full")} value={mistake} onChange={(e) => setMistake(e.target.value)}>
            <option value="">None</option>
            {MISTAKE_TYPES.map((m) => (
              <option key={m.id} value={m.id}>
                {m.label} — {m.hint}
              </option>
            ))}
          </select>
        </label>
        <label className="block">
          <span className="mb-1 block text-xs text-muted">Notes / pattern</span>
          <textarea className={cx(inputCls, "h-auto py-2")} rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Key insight, pattern, what to remember next time…" />
        </label>
        {taskId && !taskDone && outcome === "solved" && <Checkbox checked={markTask} onChange={setMarkTask} label="Also mark the roadmap task complete" />}
        <div className="flex justify-end gap-2 pt-1">
          <Button variant="ghost" onClick={onClose}>
            Cancel
          </Button>
          <Button
            variant="primary"
            disabled={!pid}
            onClick={() => {
              dispatch("DSA_ATTEMPTED", { problemId: pid, mode, outcome, minutes, ...(mistake ? { mistakeType: mistake as never } : {}), ...(notes.trim() ? { notes: notes.trim() } : {}), ...(taskId ? { taskId } : {}) });
              if (taskId && !taskDone && outcome === "solved" && markTask) dispatch("TASK_COMPLETED", { taskId });
              onClose();
            }}
          >
            Save attempt
          </Button>
        </div>
      </div>
    </Modal>
  );
}

export function Loading() {
  return <div className="py-16 text-center text-sm text-muted">Loading your progress…</div>;
}
